title: ""
description: "Data Analytics Portfolio | Tableau · Power BI"
remote_theme: "mmistakes/minimal-mistakes"
plugins: [jekyll-remote-theme, jekyll-include-cache]
markdown: kramdown

# 顶部导航
nav:
  - title: "Home"
    url: /
  - title: "Portfolio"   # 先只是一个页面的入口
    url: /portfolio/
  - title: "Certifications"
    url: /certifications/
  - title: "Blog"
    url: /blog/
  - title: "About"
    url: /about/


url: "https://fullstackchloe.com"  # 换成你的域名
baseurl: ""                        # 保持空

# 禁用RSS feed
feed:
  enabled: false

# 禁用所有feed相关功能
atom_feed:
  enabled: false
rss_feed:
  enabled: false

# 禁用footer中的feed链接
footer:
  feed_icon: false
